In [1]:
from websocket import create_connection
import json
import pandas as pd
from datetime import date
from time import sleep

In [2]:
## web socket url
socket = 'wss://data.tradingview.com/socket.io/websocket'
# change session id based on current session value
session_id = 's_h1DU5odwE8df'
## example messages to be sent
# ~m~55~m~{"m":"chart_create_session","p":["cs_yDp6P0icM81I",""]}
# ~m~117~m~{"m":"resolve_symbol","p":["cs_yDp6P0icM81I","sds_sym_1","={\"adjustment\":\"splits\",\"symbol\":\"NSE:HDFCBANK\"}"]}
# ~m~82~m~{"m":"create_series","p":["cs_yDp6P0icM81I","sds_1","s1","sds_sym_1","1W",300,""]}

downloads = './data/nifty500_5yr_daily/'

In [4]:
# create message as per template and send
def create_msg(ws, fun, arg):
    ms = json.dumps({"m":fun,"p":arg})
    msg = f'~m~{len(ms)}~m~{ms}'
    ws.send(msg)

# format result data into pandas dataframe
def format_data(data):
    start = data.find('"s":[')
    end = data.find(',"ns":')
    trimmed = data[start+4 : end]
    final_data = [x["v"] for x in json.loads(data[start+4 : end])]
    # print(final_data)
    return final_data

In [5]:
def fetch_historic_data(symbol):
    # resolve_symbol argument
    sess_msg = [session_id,""]    
    resolve_symbol = '={\"adjustment\":\"splits\",\"symbol\":\"NSE:' + symbol + '\"}'
    res_sym_msg = [session_id,"sds_sym_1",resolve_symbol]
    ser_msg = [session_id,"sds_1","s1","sds_sym_1","1D",1030,""]
    # create fresh websocket connection
    ws = create_connection(socket)
    # send messages to websocket
    create_msg(ws, 'chart_create_session', sess_msg)
    create_msg(ws, 'resolve_symbol', res_sym_msg)
    create_msg(ws, 'create_series', ser_msg)
    
    while True :
        # receive response for the messages sent
        res = ws.recv()
        if "series_completed" in res:
            formatted_data = format_data(res)
            # convert json to pandas dataframe for analysis
            df_result = pd.DataFrame(formatted_data, columns=['date', 'open', 'high', 'low', 'close', 'volume'])
            # convert epoch timestamp to date yyyy-mm-dd format
            df_result['date'] = df_result['date'].apply(lambda x : str(date.fromtimestamp(x)))
            df_result.sort_values('date', inplace=True)
            # calculate average
            df_result['avg'] = df_result.apply(lambda row : int((row['open'] + row['high'] + row['low'] + row['close'])/4), axis=1)
            # shutdown websocket connection for next iteration to work properly
            ws.shutdown()
            # break the infinite while loop
            break
    
    return df_result

In [6]:
# run for a sample symbol
df_result = fetch_historic_data('BAJAJ_AUTO')
df_result

            date     open       high        low      close     volume   avg
0     2021-01-13  3624.25  3633.0000  3577.0000  3600.8999   515154.0  3608
1     2021-01-14  3600.00  3658.6499  3545.0000  3576.0500   743848.0  3594
2     2021-01-15  3588.00  3623.0000  3541.0000  3580.3000   684649.0  3583
3     2021-01-18  3552.00  3618.0500  3505.0000  3563.7500   602004.0  3559
4     2021-01-19  3565.75  3664.0000  3561.1001  3641.0000   586410.0  3607
...          ...      ...        ...        ...        ...        ...   ...
1025  2025-02-28  8234.75  8234.7500  7886.3000  7902.9000   580155.0  8064
1026  2025-03-03  7934.95  7998.3000  7679.6000  7714.8000   497052.0  7831
1027  2025-03-04  7652.10  7680.0000  7317.0500  7333.3000  1078953.0  7495
1028  2025-03-05  7332.20  7443.3000  7301.0000  7420.3000   749464.0  7374
1029  2025-03-06  7481.00  7500.0000  7376.9500  7462.2500   917093.0  7455

[1030 rows x 7 columns]

In [8]:
# if loop breaks before completing all symbols, add the completed symbols to this list
completed_list = []

# use index/list of your choice
#/Users/abss/Desktop/Work/StockPrediction/share_analysis
nifty_500 = pd.read_csv('./data/ind_nifty500list.csv')
nifty_500

,Company Name,Industry,Symbol,Series,ISIN Code
0,360 ONE WAM Ltd.,Financial Services,360ONE,EQ,INE466L01038
1,3M India Ltd.,Diversified,3MINDIA,EQ,INE470A01017
2,ABB India Ltd.,Capital Goods,ABB,EQ,INE117A01022
3,ACC Ltd.,Construction Materials,ACC,EQ,INE012A01025
4,AIA Engineering Ltd.,Capital Goods,AIAENG,EQ,INE212H01026
...,...,...,...,...,...
495,Zee Entertainment Enterprises Ltd.,Media Entertainment & Publication,ZEEL,EQ,INE256A01028
496,Zensar Technolgies Ltd.,Information Technology,ZENSARTECH,EQ,INE520A01027
497,Zomato Ltd.,Consumer Services,ZOMATO,EQ,INE758T01015
498,Zydus Lifesciences Ltd.,Healthcare,ZYDUSLIFE,EQ,INE010B01027
499,eClerx Services Ltd.,Services,ECLERX,EQ,INE738I01010

In [9]:
symbols = list(sorted(set(nifty_500['Symbol']) - set(completed_list)))

for i, symbol in enumerate(symbols) :
    if '-' in symbol:
        symbol = symbol.replace('-', '_')
    df_result = fetch_historic_data(symbol)
    df_result.to_csv(downloads + symbol + '.csv', index=None)
    completed_list.append(symbol)
    sleep(1)
    print(i+1, symbol)

1 360ONE
2 3MINDIA
3 AADHARHFC
4 AARTIIND
5 AAVAS
6 ABB
7 ABBOTINDIA
8 ABCAPITAL
9 ABFRL
10 ABREL
11 ABSLAMC
12 ACC
13 ACE
14 ACI
15 ADANIENSOL
16 ADANIENT
17 ADANIGREEN
18 ADANIPORTS
19 ADANIPOWER
20 AEGISLOG
21 AFFLE
22 AIAENG
23 AJANTPHARM
24 AKUMS
25 ALKEM
26 ALKYLAMINE
27 ALOKINDS
28 AMBER
29 AMBUJACEM
30 ANANDRATHI
31 ANANTRAJ
32 ANGELONE
33 APARINDS
34 APLAPOLLO
35 APLLTD
36 APOLLOHOSP
37 APOLLOTYRE
38 APTUS
39 ARE&M
40 ASAHIINDIA
41 ASHOKLEY
42 ASIANPAINT
43 ASTERDM
44 ASTRAL
45 ASTRAZEN
46 ATGL
47 ATUL
48 AUBANK
49 AUROPHARMA
50 AVANTIFEED
51 AWL
52 AXISBANK
53 BAJAJ_AUTO
54 BAJAJFINSV
55 BAJAJHLDNG
56 BAJFINANCE
57 BALAMINES
58 BALKRISIND
59 BALRAMCHIN
60 BANDHANBNK
61 BANKBARODA
62 BANKINDIA
63 BASF
64 BATAINDIA
65 BAYERCROP
66 BBTC
67 BDL
68 BEL
69 BEML
70 BERGEPAINT
71 BHARATFORG
72 BHARTIARTL
73 BHARTIHEXA
74 BHEL
75 BIKAJI
76 BIOCON
77 BIRLACORPN
78 BLS
79 BLUEDART
80 BLUESTARCO
81 BOSCHLTD
82 BPCL
83 BRIGADE
84 BRITANNIA
85 BSE
86 BSOFT
87 CAMPUS
88 CAMS
89 CANBK
90 CANFINHOME
91 CAPLIPOINT
92 CARBORUNIV
93 CASTROLIND
94 CCL
95 CDSL
96 CEATLTD
97 CELLO
98 CENTRALBK
99 CENTURYPLY
100 CERA
101 CESC
102 CGCL
103 CGPOWER
104 CHALET
105 CHAMBLFERT
106 CHEMPLASTS
107 CHENNPETRO
108 CHOLAFIN
109 CHOLAHLDNG
110 CIEINDIA
111 CIPLA
112 CLEAN
113 COALINDIA
114 COCHINSHIP
115 COFORGE
116 COLPAL
117 CONCOR
118 CONCORDBIO
119 COROMANDEL
120 CRAFTSMAN
121 CREDITACC
122 CRISIL
123 CROMPTON
124 CUB
125 CUMMINSIND
126 CYIENT
127 DABUR
128 DALBHARAT
129 DATAPATTNS
130 DBREALTY
131 DEEPAKFERT
132 DEEPAKNTR
133 DELHIVERY
134 DEVYANI
135 DIVISLAB
136 DIXON
137 DLF
138 DMART
139 DOMS
140 DRREDDY
141 EASEMYTRIP
142 ECLERX
143 EICHERMOT
144 EIDPARRY
145 EIHOTEL
146 ELECON
147 ELGIEQUIP
148 EMAMILTD
149 EMCURE
150 ENDURANCE
151 ENGINERSIN
152 EQUITASBNK
153 ERIS
154 ESCORTS
155 EXIDEIND
156 FACT
157 FEDERALBNK
158 FINCABLES
159 FINEORG
160 FINPIPE
161 FIVESTAR
162 FLUOROCHEM
163 FORTIS
164 FSL
165 GAEL
166 GAIL
167 GESHIP
168 GICRE
169 GILLETTE
170 GLAND
171 GLAXO
172 GLENMARK
173 GMDCLTD
174 GMRAIRPORT
175 GNFC
176 GODFRYPHLP
177 GODIGIT
178 GODREJAGRO
179 GODREJCP
180 GODREJIND
181 GODREJPROP
182 GPIL
183 GPPL
184 GRANULES
185 GRAPHITE
186 GRASIM
187 GRINDWELL
188 GRINFRA
189 GRSE
190 GSFC
191 GSPL
192 GUJGASLTD
193 GVT&D
194 HAL
195 HAPPSTMNDS
196 HAVELLS
197 HBLENGINE
198 HCLTECH
199 HDFCAMC
200 HDFCBANK
201 HDFCLIFE
202 HEG
203 HEROMOTOCO
204 HFCL
205 HINDALCO
206 HINDCOPPER
207 HINDPETRO
208 HINDUNILVR
209 HINDZINC
210 HOMEFIRST
211 HONASA
212 HONAUT
213 HSCL
214 HUDCO
215 ICICIBANK
216 ICICIGI
217 ICICIPRULI
218 IDBI
219 IDEA
220 IDFCFIRSTB
221 IEX
222 IFCI
223 IGL
224 IIFL
225 INDGN
226 INDHOTEL
227 INDIACEM
228 INDIAMART
229 INDIANB
230 INDIGO
231 INDUSINDBK
232 INDUSTOWER
233 INFY
234 INOXINDIA
235 INOXWIND
236 INTELLECT
237 IOB
238 IOC
239 IPCALAB
240 IRB
241 IRCON
242 IRCTC
243 IREDA
244 IRFC
245 ISEC
246 ITC
247 ITI
248 J&KBANK
249 JBCHEPHARM
250 JBMA
251 JINDALSAW
252 JINDALSTEL
253 JIOFIN
254 JKCEMENT
255 JKLAKSHMI
256 JKTYRE
257 JMFINANCIL
258 JPPOWER
259 JSL
260 JSWENERGY
261 JSWINFRA
262 JSWSTEEL
263 JUBLFOOD
264 JUBLINGREA
265 JUBLPHARMA
266 JUSTDIAL
267 JWL
268 JYOTHYLAB
269 JYOTICNC
270 KAJARIACER
271 KALYANKJIL
272 KANSAINER
273 KARURVYSYA
274 KAYNES
275 KEC
276 KEI
277 KFINTECH
278 KIMS
279 KIRLOSBROS
280 KIRLOSENG
281 KNRCON
282 KOTAKBANK
283 KPIL
284 KPITTECH
285 KPRMILL
286 KSB
287 LALPATHLAB
288 LATENTVIEW
289 LAURUSLABS
290 LEMONTREE
291 LICHSGFIN
292 LICI
293 LINDEINDIA
294 LLOYDSME
295 LODHA
296 LT
297 LTF
298 LTIM
299 LTTS
300 LUPIN
301 M&M
302 M&MFIN
303 MAHABANK
304 MAHLIFE
305 MAHSEAMLES
306 MANAPPURAM
307 MANKIND
308 MANYAVAR
309 MAPMYINDIA
310 MARICO
311 MARUTI
312 MASTEK
313 MAXHEALTH
314 MAZDOCK
315 MCX
316 MEDANTA
317 METROBRAND
318 METROPOLIS
319 MFSL
320 MGL
321 MINDACORP
322 MMTC
323 MOTHERSON
324 MOTILALOFS
325 MPHASIS
326 MRF
327 MRPL
328 MSUMI
329 MUTHOOTFIN
330 NAM_INDIA
331 NATCOPHARM
332 NATIONALUM
333 NAUKRI
334 NAVINFLUOR
335 NBCC
336 NCC
337 NESTLEIND
338 NETWEB
339 NETWORK18
340 NEWGEN
341 NH
342 NHPC
343 NIACL
344 NLCINDIA
345 NMDC
346 NSLNISP
347 NTPC
348 NUVAMA
349 NUVOCO
350 NYKAA
351 OBEROIRLTY
352 OFSS
353 OIL
354 OLECTRA
355 ONGC
356 PAGEIND
357 PATANJALI
358 PAYTM
359 PCBL
360 PEL
361 PERSISTENT
362 PETRONET
363 PFC
364 PFIZER
365 PGHH
366 PHOENIXLTD
367 PIDILITIND
368 PIIND
369 PNB
370 PNBHOUSING
371 PNCINFRA
372 POLICYBZR
373 POLYCAB
374 POLYMED
375 POONAWALLA
376 POWERGRID
377 POWERINDIA
378 PPLPHARMA
379 PRAJIND
380 PRESTIGE
381 PTCIL
382 PVRINOX
383 QUESS
384 RADICO
385 RAILTEL
386 RAINBOW
387 RAJESHEXPO
388 RAMCOCEM
389 RATNAMANI
390 RAYMOND
391 RBLBANK
392 RCF
393 RECLTD
394 REDINGTON
395 RELIANCE
396 RENUKA
397 RHIM
398 RITES
399 RKFORGE
400 ROUTE
401 RRKABEL
402 RTNINDIA
403 RVNL
404 SAIL
405 SAMMAANCAP
406 SANOFI
407 SAPPHIRE
408 SAREGAMA
409 SBFC
410 SBICARD
411 SBILIFE
412 SBIN
413 SCHAEFFLER
414 SCHNEIDER
415 SCI
416 SHREECEM
417 SHRIRAMFIN
418 SHYAMMETL
419 SIEMENS
420 SIGNATURE
421 SJVN
422 SKFINDIA
423 SOBHA
424 SOLARINDS
425 SONACOMS
426 SONATSOFTW
427 SPARC
428 SRF
429 STARHEALTH
430 SUMICHEM
431 SUNDARMFIN
432 SUNDRMFAST
433 SUNPHARMA
434 SUNTV
435 SUPREMEIND
436 SUVENPHAR
437 SUZLON
438 SWANENERGY
439 SWSOLAR
440 SYNGENE
441 SYRMA
442 TANLA
443 TATACHEM
444 TATACOMM
445 TATACONSUM
446 TATAELXSI
447 TATAINVEST
448 TATAMOTORS
449 TATAPOWER
450 TATASTEEL
451 TATATECH
452 TBOTEK
453 TCS
454 TECHM
455 TECHNOE
456 TEJASNET
457 THERMAX
458 TIINDIA
459 TIMKEN
460 TITAGARH
461 TITAN
462 TORNTPHARM
463 TORNTPOWER
464 TRENT
465 TRIDENT
466 TRITURBINE
467 TRIVENI
468 TTML
469 TVSMOTOR
470 TVSSCS
471 UBL
472 UCOBANK
473 UJJIVANSFB
474 ULTRACEMCO
475 UNIONBANK
476 UNITDSPR
477 UNOMINDA
478 UPL
479 USHAMART
480 UTIAMC
481 VARROC
482 VBL
483 VEDL
484 VGUARD
485 VIJAYA
486 VINATIORGA
487 VIPIND
488 VOLTAS
489 VTL
490 WELCORP
491 WELSPUNLIV
492 WESTLIFE
493 WHIRLPOOL
494 WIPRO
495 YESBANK
496 ZEEL
497 ZENSARTECH
498 ZFCVINDIA
499 ZOMATO
500 ZYDUSLIFE